**

!fireviewer-spatial/
!fireviewer-spatial/requirements.runpod-map-production.txt
!fireviewer-spatial/blender/
!fireviewer-spatial/blender/**
!fireviewer-spatial/omniverse/
!fireviewer-spatial/omniverse/**
fireviewer-spatial/blender/test_*.py
fireviewer-spatial/omniverse/test_*.py

**/__pycache__/**
**/*.pyc
**/.pytest_cache/**
**/.ruff_cache/**
**/*.part
