**

!fireviewer-spatial/
!fireviewer-spatial/requirements.simple-production-api.txt
!fireviewer-spatial/blender/
!fireviewer-spatial/blender/**
!fireviewer-spatial/omniverse/
!fireviewer-spatial/omniverse/**
fireviewer-spatial/blender/test_*.py
fireviewer-spatial/omniverse/test_*.py
fireviewer-spatial/blender/render_ground_atlas_qa.py

!fireviewer-sdg/
!fireviewer-sdg/asset4sim/
!fireviewer-sdg/asset4sim/generated_hunyuan3d_v2/
!fireviewer-sdg/asset4sim/generated_hunyuan3d_v2/reference-manifest.json
!fireviewer-sdg/asset4sim/generated_hunyuan3d_v2/simready_final_0001_0294/
!fireviewer-sdg/asset4sim/generated_hunyuan3d_v2/simready_final_0001_0294/**
!fireviewer-sdg/asset4sim/generated_otherway_betterquality/
!fireviewer-sdg/asset4sim/generated_otherway_betterquality/**

**/__pycache__/**
**/*.pyc
**/.pytest_cache/**
**/.ruff_cache/**
**/*.part
